"""add stripe_customer_id to users

Revision ID: 47b9c1a57613
Revises: 686b8d9aba0c
Create Date: 2026-08-15 00:00:10.293387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b9c1a57613'
down_revision = '686b8d9aba0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
