"""add reason difficulty category to words

Revision ID: 4b37728f9e0b
Revises: f639bf5c2fb1
Create Date: 2026-08-11 23:35:55.852221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b37728f9e0b'
down_revision = 'f639bf5c2fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
