"""add unique constraints to exam_word_stats, wordbook_words, user_word_history, tags

Revision ID: 686b8d9aba0c
Revises: aff016ccc94a
Create Date: 2026-08-13 14:35:27.658755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686b8d9aba0c'
down_revision = 'aff016ccc94a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_word_stats', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_exam_word_stats', ['word_master_id', 'exam_id'])

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tags', ['type', 'name'])

    with op.batch_alter_table('user_word_history', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_word_history', ['user_id', 'word_master_id'])

    with op.batch_alter_table('wordbook_words', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_wordbook_words', ['wordbook_id', 'word_master_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordbook_words', schema=None) as batch_op:
        batch_op.drop_constraint('uq_wordbook_words', type_='unique')

    with op.batch_alter_table('user_word_history', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_word_history', type_='unique')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tags', type_='unique')

    with op.batch_alter_table('exam_word_stats', schema=None) as batch_op:
        batch_op.drop_constraint('uq_exam_word_stats', type_='unique')

    # ### end Alembic commands ###
