"""allow guest wordlists (user_id nullable)

Revision ID: 798508b3999f
Revises: 643648584022
Create Date: 2026-08-15 01:06:08.505898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798508b3999f'
down_revision = '643648584022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordlists', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordlists', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
