"""add word master, exam, folder, wordbook tables

Revision ID: aff016ccc94a
Revises: 4b37728f9e0b
Create Date: 2026-08-12 00:06:54.025034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff016ccc94a'
down_revision = '4b37728f9e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(length=255), nullable=False),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('pronunciation', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word_master', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_master_lemma'), ['lemma'], unique=True)

    op.create_table('exam_domain_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_domain_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_domain_rules_exam_id'), ['exam_id'], unique=False)

    op.create_table('exam_word_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_master_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('frequency_score', sa.Float(), nullable=True),
    sa.Column('last_appeared', sa.String(length=20), nullable=True),
    sa.Column('domain_relevance', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['word_master_id'], ['word_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_word_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_word_stats_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_word_stats_word_master_id'), ['word_master_id'], unique=False)

    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_folders_user_id'), ['user_id'], unique=False)

    op.create_table('meanings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_master_id', sa.Integer(), nullable=False),
    sa.Column('meaning_ja', sa.Text(), nullable=False),
    sa.Column('example_en', sa.Text(), nullable=True),
    sa.Column('example_ja', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['word_master_id'], ['word_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meanings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meanings_word_master_id'), ['word_master_id'], unique=False)

    op.create_table('user_word_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_master_id', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_master_id'], ['word_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_word_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_word_history_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_word_history_word_master_id'), ['word_master_id'], unique=False)

    op.create_table('word_metadata',
    sa.Column('word_master_id', sa.Integer(), nullable=False),
    sa.Column('cefr_level', sa.String(length=2), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['word_master_id'], ['word_master.id'], ),
    sa.PrimaryKeyConstraint('word_master_id')
    )
    op.create_table('word_tags',
    sa.Column('word_master_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['word_master_id'], ['word_master.id'], ),
    sa.PrimaryKeyConstraint('word_master_id', 'tag_id')
    )
    op.create_table('wordbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_words_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wordbooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wordbooks_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wordbooks_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wordbooks_user_id'), ['user_id'], unique=False)

    op.create_table('wordbook_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wordbook_id', sa.Integer(), nullable=False),
    sa.Column('word_master_id', sa.Integer(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['word_master_id'], ['word_master.id'], ),
    sa.ForeignKeyConstraint(['wordbook_id'], ['wordbooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wordbook_words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wordbook_words_word_master_id'), ['word_master_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wordbook_words_wordbook_id'), ['wordbook_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wordbook_words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wordbook_words_wordbook_id'))
        batch_op.drop_index(batch_op.f('ix_wordbook_words_word_master_id'))

    op.drop_table('wordbook_words')
    with op.batch_alter_table('wordbooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wordbooks_user_id'))
        batch_op.drop_index(batch_op.f('ix_wordbooks_folder_id'))
        batch_op.drop_index(batch_op.f('ix_wordbooks_exam_id'))

    op.drop_table('wordbooks')
    op.drop_table('word_tags')
    op.drop_table('word_metadata')
    with op.batch_alter_table('user_word_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_word_history_word_master_id'))
        batch_op.drop_index(batch_op.f('ix_user_word_history_user_id'))

    op.drop_table('user_word_history')
    with op.batch_alter_table('meanings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meanings_word_master_id'))

    op.drop_table('meanings')
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_folders_user_id'))

    op.drop_table('folders')
    with op.batch_alter_table('exam_word_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_word_stats_word_master_id'))
        batch_op.drop_index(batch_op.f('ix_exam_word_stats_exam_id'))

    op.drop_table('exam_word_stats')
    with op.batch_alter_table('exam_domain_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_domain_rules_exam_id'))

    op.drop_table('exam_domain_rules')
    with op.batch_alter_table('word_master', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_master_lemma'))

    op.drop_table('word_master')
    op.drop_table('tags')
    op.drop_table('exams')
    # ### end Alembic commands ###
